import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("cars").del();

  // Inserts seed entries
  await knex("cars").insert([
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Ford",
      model: "F150",
      transmission: "Automatic",
      plate: "B 7869 GUH",
      year: 2022,
      driver_service: false,
      rent_per_day: 250000,
      capacity: 6,
      type: "Regular Cab Pickup",
      category: "large",
      options: JSON.stringify([
        "Cruise Control",
        "Tinted Glass",
        "AM/FM Stereo",
      ]),
      specs: JSON.stringify([
        "Brake assist",
        "Leather-wrapped shift knob",
        "Glove box lamp",
        "Air conditioning w/in-cabin microfilter",
        "Body color folding remote-controlled pwr mirrors",
        "Dual-stage front airbags w/occupant classification system",
      ]),
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Suzuki",
      model: "Esteem",
      transmission: "Manual",
      plate: "B 5417 BCS",
      year: 1998,
      driver_service: true,
      rent_per_day: 200000,
      image:
        "https://res.cloudinary.com/de3zdoakr/image/upload/v1718256597/binar-car-rental/upload/data/car/B%205417%20BCS.png",
      capacity: 4,
      type: "Sedan",
      category: "small",
      description:
        "Did you know you have rights? The Constitution says you do, and so sdi I. I believe that until proven guilty, every man, woman and child is innocent.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Mitsubishi",
      model: "Evo Lancer 4",
      transmission: "Manual",
      plate: "D 8970 BDG",
      year: 2001,
      driver_service: true,
      rent_per_day: 200000,
      image:
        "https://res.cloudinary.com/de3zdoakr/image/upload/v1718255925/binar-car-rental/upload/data/car/D%208970%20BDG.jpg",
      capacity: 4,
      type: "Sedan",
      category: "small",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "BMW",
      model: "X5",
      transmission: "Automatic",
      plate: "A 1234 AB",
      year: 2018,
      driver_service: false,
      rent_per_day: 800000,
      capacity: 6,
      type: "Convertible",
      category: "small",
      options: JSON.stringify([
        "Keyless Entry",
        "Power Windows",
        "MP3 (Single Disc)",
        "CD (Multi Disc)",
        "Navigation",
      ]),
      specs: JSON.stringify([
        "Rear passenger map pockets",
        "Electrochromic rearview mirror",
        "Dual chrome exhaust tips",
        "Locking glove box",
        "Pwr front vented disc/rear drum brakes",
      ]),
      description:
        "Rear passenger map pockets. Electrochromic rearview mirror. Dual chrome exhaust tips. Locking glove box.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Lincoln",
      model: "MKZ",
      transmission: "Automanual",
      plate: "B 5678 CD",
      year: 2021,
      driver_service: true,
      rent_per_day: 900000,
      capacity: 6,
      type: "Sedan",
      category: "medium",
      options: JSON.stringify([
        "Bucket Seats",
        "Airbag: Passenger",
        "Airbag: Driver",
        "Power Seats",
        "Airbag: Side",
        "Antilock Brakes",
        "CD (Multi Disc)",
      ]),
      specs: JSON.stringify([
        "Driver & front passenger map pockets",
        "Direct-type tire pressure monitor system",
        "Cargo area lamp",
        "Glove box lamp",
        "Silver finish interior door handles",
        "Driver & front passenger advanced multistage airbags w/occupant sensors",
        "Silver accent IP trim finisher -inc: silver shifter finisher",
        "Fasten seat belt warning light/chime",
      ]),
      description:
        "Driver & front passenger map pockets. Direct-type tire pressure monitor system. Cargo area lamp. Glove box lamp.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "BMW",
      model: "M5",
      transmission: "Manual",
      plate: "D 910 EF",
      year: 2018,
      driver_service: false,
      rent_per_day: 900000,
      capacity: 6,
      type: "Hatchback",
      category: "medium",
      options: JSON.stringify([
        "Alloy Wheels",
        "Power Locks",
        "A/C: Rear",
        "MP3 (Single Disc)",
        "Airbag: Driver",
        "A/C: Front",
        "Tinted Glass",
        "Alloy Wheels",
        "Alarm",
      ]),
      specs: JSON.stringify([
        '6.1L SRT V8 "Hemi" engine',
        "Multi-info display -inc: driving range, average MPG, current MPG, average speed, outside temp, elapsed time, maintenance & diagnostic messages",
        "Front & rear passenger folding assist grips",
        "Electronic throttle control system w/intelligence (ETCS-i)",
        "Pwr tilt/slide moonroof -inc: 1-touch open/close",
        "Acoustic glass windshield",
      ]),
      description: '6.1L SRT V8 "Hemi" engine.',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Lincoln",
      model: "Navigator",
      transmission: "Automatic",
      plate: "F 1123 GH",
      year: 2020,
      driver_service: true,
      rent_per_day: 200000,
      capacity: 2,
      type: "Minivan",
      category: "small",
      options: JSON.stringify([
        "CD (Multi Disc)",
        "Cruise Control",
        "Power Locks",
        "Alloy Wheels",
        "Tow Package",
      ]),
      specs: JSON.stringify([
        "Body color sill extension",
        "Torsion beam rear suspension w/stabilizer bar",
        "Front & rear passenger folding assist grips",
        "Electronic control braking (ECB)",
        "Black windshield molding",
      ]),
      description: '6.1L SRT V8 "Hemi" engine.',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Ford",
      model: "Fiesta",
      transmission: "Automanual",
      plate: "T 4567 IJ",
      year: 2016,
      driver_service: false,
      rent_per_day: 900000,
      capacity: 4,
      type: "Hatchback",
      category: "small",
      options: JSON.stringify([
        "Leather Interior",
        "A/C: Rear",
        "CD (Multi Disc)",
        "Airbag: Side",
        "MP3 (Multi Disc)",
      ]),
      specs: JSON.stringify([
        "Tilt steering column",
        "Carpeted cargo area",
        "Tip start system",
        "Leather-wrapped shift knob",
        "Enhanced accident response system unlocks the doors, shuts off the fuel pump and turns on interior lights after airbag deploys",
        "Compact spare tire",
      ]),
      description:
        "Tilt steering column. Carpeted cargo area. Tip start system. Leather-wrapped shift knob.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Honda",
      model: "Accord",
      transmission: "Automatic",
      plate: "Z 8910 KL",
      year: 2020,
      driver_service: true,
      rent_per_day: 900000,
      capacity: 4,
      type: "Sedan",
      category: "small",
      options: JSON.stringify([
        "AM/FM Stereo",
        "Power Locks",
        "Power Windows",
        "MP3 (Single Disc)",
        "A/C: Rear",
      ]),
      specs: JSON.stringify([
        "Silver finish interior door handles",
        "160-amp alternator",
        "Tire pressure monitoring system (TPMS)",
        "Cloth covered headliner",
        "625-amp maintenance-free battery",
        "Torsion beam rear suspension w/stabilizer bar",
        "Impact-dissipating upper interior trim",
        "Dual front 2-stage airbags -inc: passenger occupant classification system w/twin-chamber airbag",
      ]),
      description:
        "Silver finish interior door handles. 160-amp alternator. Tire pressure monitoring system (TPMS). Cloth covered headliner.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Lincoln",
      model: "Navigator",
      transmission: "Manual",
      plate: "E 2345 MN",
      year: 2014,
      driver_service: false,
      rent_per_day: 300000,
      capacity: 2,
      type: "Regular Cab Pickup",
      category: "large",
      options: JSON.stringify([
        "Fog Lights",
        "Memory Seats",
        "Rear Window Defroster",
        "Integrated Phone",
        "Power Locks",
        "A/C: Rear",
      ]),
      specs: JSON.stringify([
        "XM satellite radio receiver -inc: 90 day trial subscription",
        "Dual front illuminated visor vanity mirrors",
        "Front door tinted glass",
        "Body color door handles",
        "Chrome bodyside molding",
      ]),
      description:
        "XM satellite radio receiver -inc: 90 day trial subscription. Dual front illuminated visor vanity mirrors.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Buick",
      model: "LaCrosse",
      transmission: "Automatic",
      plate: "H 6789 OP",
      year: 2012,
      driver_service: true,
      rent_per_day: 1000000,
      capacity: 6,
      type: "Extended Cab Pickup",
      category: "large",
      options: JSON.stringify([
        "CD (Multi Disc)",
        "Keyless Entry",
        "Cassette Player",
        "Power Windows",
        "Rear Window Wiper",
        "CD (Single Disc)",
        "Third Row Seats",
      ]),
      specs: JSON.stringify([
        "Rear reading & courtesy lamps",
        "Zone body construction -inc: front/rear crumple zones, hood deformation point",
        "4-wheel/4-channel anti-lock brake system (ABS)",
        "Anti-lock 4-wheel performance disc brakes",
        "200mm front axle",
        "Dual front knee airbags",
      ]),
      description:
        "Rear reading & courtesy lamps. Zone body construction -inc: front/rear crumple zones, hood deformation point.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "BMW",
      model: "X5",
      transmission: "Manual",
      plate: "G 1011 QR",
      year: 2019,
      driver_service: false,
      rent_per_day: 300000,
      capacity: 6,
      type: "Hatchback",
      category: "medium",
      options: JSON.stringify([
        "Third Row Seats",
        "Bucket Seats",
        "Integrated Phone",
        "Navigation",
        "Leather Interior",
      ]),
      specs: JSON.stringify([
        "Cargo compartment lamp",
        "Body color fascias w/bright insert",
        "Front/rear stabilizer bars",
        "Electrochromic pwr folding heated mirrors w/memory -inc: puddle lamps, integrated turn signals, auto reverse tilt-down",
        "Multi-info display -inc: driving range, average MPG, current MPG, average speed, outside temp, elapsed time, maintenance & diagnostic messages",
      ]),
      description:
        "Cargo compartment lamp. Body color fascias w/bright insert. Front/rear stabilizer bars.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Chevy",
      model: "Malibu",
      transmission: "Automatic",
      plate: "K 1213 ST",
      year: 2019,
      driver_service: true,
      rent_per_day: 700000,
      capacity: 2,
      type: "Coupe",
      category: "small",
      options: JSON.stringify([
        "Alloy Wheels",
        "Power Windows",
        "Alarm",
        "Bucket Seats",
      ]),
      specs: JSON.stringify([
        "Cloth covered headliner",
        "Sentry Key theft deterrent system",
        "Air conditioning w/in-cabin microfilter",
        "Driver & front passenger map pockets",
        "Security alarm",
        "Dual bright exhaust tips",
        "Compact spare tire",
      ]),
      description:
        "Cloth covered headliner. Sentry Key theft deterrent system. Air conditioning w/in-cabin microfilter.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "BMW",
      model: "X3",
      transmission: "Automanual",
      plate: "R 1415 UV",
      year: 2018,
      driver_service: false,
      rent_per_day: 800000,
      capacity: 4,
      type: "Passenger Van",
      category: "small",
      options: JSON.stringify([
        "Premium Sound",
        "Fog Lights",
        "Premium Sound",
        "Airbag: Side",
        "Power Seats",
        "Airbag: Driver",
        "Power Steering",
        "Alarm",
      ]),
      specs: JSON.stringify([
        "Multi-reflector halogen headlamps",
        "Speed control",
        "Anti-lock brake system (ABS) -inc: electronic brake force distribution (EBD), brake assist",
        "Laminated side window glass",
        "Acoustic glass windshield",
        "Back-up camera",
        "Direct-type tire pressure monitor system",
        "All-position 3-point seat belts -inc: outboard pretensioners & force limiters, dual front pwr shoulder height adjusters, rear outboard emergency auto locking retractors, driver emergency locking retractor",
      ]),
      description: "Multi-reflector halogen headlamps. Speed control.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Chevy",
      model: "Malibu",
      transmission: "Manual",
      plate: "AD 1819 YZ",
      year: 2020,
      driver_service: false,
      rent_per_day: 700000,
      capacity: 2,
      type: "Regular Cab Pickup",
      category: "large",
      options: JSON.stringify([
        "Bucket Seats",
        "Power Seats",
        "CD (Multi Disc)",
        "Bucket Seats",
        "Navigation",
        "Rear Window Defroster",
        "Fog Lights",
      ]),
      specs: JSON.stringify([
        "Front/rear side curtain airbags",
        "Front & rear side curtain airbags",
        "Body color front license plate brow",
        "Rear body-color spoiler",
        "Reversible/waterproof cargo storage",
        "Front & rear side curtain airbags",
      ]),
      description:
        "Front/rear side curtain airbags. Front & rear side curtain airbags. Body color front license plate brow. Rear body-color spoiler.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Chevy",
      model: "Malibu",
      transmission: "CVT",
      plate: "AB 1617 WX",
      year: 2017,
      driver_service: true,
      rent_per_day: 900000,
      capacity: 6,
      type: "SUV",
      category: "large",
      options: JSON.stringify([
        "Memory Seats",
        "Cassette Player",
        "Alarm",
        "Power Steering",
        "Keyless Entry",
      ]),
      specs: JSON.stringify([
        "Leather-wrapped shift knob",
        "Dual front illuminated visor vanity mirrors",
        "Battery saver",
        "Driver & front passenger map pockets",
        "Deluxe insulation group",
      ]),
      description:
        "Leather-wrapped shift knob. Dual front illuminated visor vanity mirrors. Battery saver. Driver & front passenger map pockets.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Chevy",
      model: "Silverado",
      transmission: "Automanual",
      plate: "AG 2223 BB",
      year: 2021,
      driver_service: false,
      rent_per_day: 200000,
      capacity: 6,
      type: "Convertible",
      category: "medium",
      options: JSON.stringify([
        "Leather Interior",
        "Alloy Wheels",
        "MP3 (Single Disc)",
        "Airbag: Driver",
        "Cruise Control",
        "Cassette Player",
      ]),
      specs: JSON.stringify([
        "Rear window defroster",
        "High performance suspension",
        "1.8L DOHC 16-valve I4 engine -inc: engine cover",
        "Air conditioning w/in-cabin microfilter",
        "4-wheel ventilated pwr disc brakes -inc: brake override system",
      ]),
      description:
        "Rear window defroster. High performance suspension. 1.8L DOHC 16-valve I4 engine -inc: engine cover.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Lincoln",
      model: "MKS",
      transmission: "Automanual",
      plate: "AE 2021 AA",
      year: 2017,
      driver_service: true,
      rent_per_day: 900000,
      capacity: 4,
      type: "Regular Cab Pickup",
      category: "large",
      options: JSON.stringify([
        "Third Row Seats",
        "CD (Single Disc)",
        "Alloy Wheels",
        "Power Windows",
        "A/C: Front",
        "Memory Seats",
        "Cruise Control",
        "CD (Single Disc)",
      ]),
      specs: JSON.stringify([
        "Remote fuel lid release",
        "Electronic parking brake",
        "Daytime running lights (DRL)",
        "Silver finish interior door handles",
        "Back-up camera",
        "Highline door trim panel",
        "Pwr front vented disc/rear drum brakes",
      ]),
      description:
        "Remote fuel lid release. Electronic parking brake. Daytime running lights (DRL). Silver finish interior door handles. Back-up camera.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Chevy",
      model: "SIlverado",
      transmission: "Automanual",
      plate: "S 2425 CC",
      year: 2021,
      driver_service: false,
      rent_per_day: 200000,
      capacity: 6,
      type: "Convertible",
      category: "medium",
      options: JSON.stringify([
        "Leather Interior",
        "Alloy Wheels",
        "MP3 (Single Disc)",
        "Airbag: Driver",
        "Cruise Control",
        "Cassette Player",
      ]),
      specs: JSON.stringify([
        "Rear window defroster",
        "High performance suspension",
        "1.8L DOHC 16-valve I4 engine -inc: engine cover",
        "Air conditioning w/in-cabin microfilter",
        "4-wheel ventilated pwr disc brakes -inc: brake override system",
      ]),
      description:
        "Rear window defroster. High performance suspension. 1.8L DOHC 16-valve I4 engine -inc: engine cover.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Lincoln",
      model: "MKS",
      transmission: "Automanual",
      plate: "W 2627 DD",
      year: 2015,
      driver_service: true,
      rent_per_day: 1000000,
      capacity: 2,
      type: "Regular Cab Pickup",
      category: "small",
      options: JSON.stringify([
        "Alarm",
        "Airbag: Passenger",
        "Cassette Player",
        "Moonroof/Sunroof",
        "Antilock Brakes",
      ]),
      specs: JSON.stringify([
        "Energy absorbing steering column",
        "3-point ELR/ALR front passenger seat belt w/pretensioner & load limiter",
        "HomeLink universal transceiver",
        "Battery saver",
        "(2) aux 12V pwr outlets -inc: (1) in center console, (1) w/cigarette lighter",
        "LATCH-ready child seat anchor system",
        "Passenger assist handles",
        "XM satellite radio receiver -inc: 90 day trial subscription",
      ]),
      description:
        "Energy absorbing steering column. 3-point ELR/ALR front passenger seat belt w/pretensioner & load limiter.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Dodge",
      model: "Ram",
      transmission: "CVT",
      plate: "L 2829 EE",
      year: 2014,
      driver_service: false,
      rent_per_day: 700000,
      capacity: 6,
      type: "Sedan",
      category: "medium",
      options: JSON.stringify([
        "Moonroof/Sunroof",
        "Cassette Player",
        "Antilock Brakes",
        "Memory Seats",
        "MP3 (Single Disc)",
        "Leather Interior",
        "CD (Single Disc)",
      ]),
      specs: JSON.stringify([
        "3-point ELR/ALR front passenger seat belt w/pretensioner & load limiter",
        "Rear passenger map pockets",
        "Black roof molding",
        "Anti-lock brake system (ABS) -inc: electronic brake force distribution (EBD), brake assist",
        "Variable intermittent windshield wipers w/mist function",
        "Roof mounted antenna",
      ]),
      description:
        "3-point ELR/ALR front passenger seat belt w/pretensioner & load limiter. Rear passenger map pockets. Black roof molding.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Ford",
      model: "F150",
      transmission: "Convertible",
      plate: "M 3031 FF",
      year: 2021,
      driver_service: true,
      rent_per_day: 600000,
      capacity: 6,
      type: "Convertible",
      category: "medium",
      options: JSON.stringify([
        "CD (Single Disc)",
        "Airbag: Driver",
        "Antilock Brakes",
        "A/C: Rear",
        "Memory Seats",
        "Third Row Seats",
      ]),
      specs: JSON.stringify([
        "All-position 3-point seat belts -inc: outboard pretensioners & force limiters, dual front pwr shoulder height adjusters, rear outboard emergency auto locking retractors, driver emergency locking retractor",
        "Body color door handles",
        "Front & rear passenger folding assist grips",
        "Rear-window defogger w/auto-off timer",
        "160-amp alternator",
        "Body color door handles",
        "Battery saver",
        "First aid kit",
        "Immobilizer system",
      ]),
      description:
        "3-point ELR/ALR front passenger seat belt w/pretensioner & load limiter. Rear passenger map pockets. Black roof molding.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Audi",
      model: "A4",
      transmission: "Automatic",
      plate: "N 3233 GG",
      year: 2012,
      driver_service: true,
      rent_per_day: 700000,
      capacity: 6,
      type: "Crew Cab Pickup",
      category: "medium",
      options: JSON.stringify([
        "Navigation",
        "Rear Window Wiper",
        "Tow Package",
        "MP3 (Multi Disc)",
        "Bucket Seats",
      ]),
      specs: JSON.stringify([
        "Pwr accessory delay",
        "Tire pressure monitoring system (TPMS)",
        "Tilt/telescoping steering column",
        "Electronic throttle control system w/intelligence (ETCS-i)",
        "Front/rear crumple zones",
        "Rear door child safety locks",
        "Child safety rear door locks",
      ]),
      description:
        "Pwr accessory delay. Tire pressure monitoring system (TPMS). Tilt/telescoping steering column.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Audi",
      model: "S5",
      transmission: "Automatic",
      plate: "BL 3637 II",
      year: 2020,
      driver_service: false,
      rent_per_day: 300000,
      capacity: 6,
      type: "Coupe",
      category: "medium",
      options: JSON.stringify([
        "Memory Seats",
        "Power Locks",
        "Fog Lights",
        "Tinted Glass",
        "Rear Window Wiper",
        "Airbag: Passenger",
        "Power Locks",
        "Tow Package",
      ]),
      specs: JSON.stringify([
        "Pwr front vented disc/rear drum brakes",
        "Pwr windows -inc: 1-touch open/close",
        "Cloth covered headliner",
        "Foldable front door storage pockets",
        "Dual-stage front airbags w/occupant classification system",
        "Battery saver",
        '20" x 9.0" front & 20" x 10.0" rear aluminum wheels',
        "Cargo compartment lamp",
      ]),
      description:
        "Pwr front vented disc/rear drum brakes. Pwr windows -inc: 1-touch open/close. Cloth covered headliner.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Dodge",
      model: "Durango",
      transmission: "Manual",
      plate: "P 3435 HH",
      year: 2013,
      driver_service: false,
      rent_per_day: 400000,
      capacity: 6,
      type: "SUV",
      category: "large",
      options: JSON.stringify([
        "Memory Seats",
        "Integrated Phone",
        "Airbag: Driver",
        "Leather Interior",
        "Cassette Player",
        "Airbag: Passenger",
      ]),
      specs: JSON.stringify([
        "Floor carpeting",
        "Electric speed-sensitive variable-assist pwr steering",
        "Dana 44/226mm rear axle",
        "Roof mounted antenna",
        "Fixed long mast antenna",
      ]),
      description:
        "Floor carpeting. Electric speed-sensitive variable-assist pwr steering. Dana 44/226mm rear axle. Roof mounted antenna.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Toyota",
      model: "Camry",
      transmission: "Automatic",
      plate: "BB 3839 JJ",
      year: 2022,
      driver_service: true,
      rent_per_day: 200000,
      capacity: 6,
      type: "Extended Cab Pickup",
      category: "medium",
      options: JSON.stringify([
        "Rear Window Defroster",
        "MP3 (Single Disc)",
        "Power Steering",
        "Antilock Brakes",
        "Tow Package",
        "Fog Lights",
        "AM/FM Stereo",
        "Alarm",
      ]),
      specs: JSON.stringify([
        "Intermittent rear wiper w/washer",
        "Energy absorbing front/rear bumpers",
        "Engine mounts -inc: (2) solid, (1) liquid-filled",
        "Tire pressure monitoring display",
        "Foldable front door storage pockets",
        "Child safety rear door locks",
        "Front/rear aluminum multi-link double joint suspension w/coil springs",
        "Laminated side window glass",
        "Silver accent IP trim finisher -inc: silver shifter finisher",
      ]),
      description:
        "Intermittent rear wiper w/washer. Energy absorbing front/rear bumpers. Engine mounts -inc: (2) solid, (1) liquid-filled.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Nissan",
      model: "Pathfiner",
      transmission: "Automatic",
      plate: "BK 4041 KK",
      year: 2022,
      driver_service: false,
      rent_per_day: 600000,
      capacity: 6,
      type: "Sedan",
      category: "medium",
      options: JSON.stringify([
        "Moonroof/Sunroof",
        "Power Seats",
        "CD (Single Disc)",
        "Airbag: Passenger",
        "Alarm",
        "Power Seats",
        "Cruise Control",
      ]),
      specs: JSON.stringify([
        "200mm front axle",
        "Roof mounted antenna",
        "Cargo compartment cover",
        "Rear bench seat -inc: (3) adjustable headrests",
        "Front/rear aluminum multi-link double joint suspension w/coil springs",
        "Reclining front bucket seats -inc: active head restraints, double-thickness foam in front seats",
      ]),
      description:
        "200mm front axle. Roof mounted antenna. Cargo compartment cover. Rear bench seat -inc: (3) adjustable headrests.",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      created_by: "muhllis.ahmad@gmail.com",
      manufacture: "Honda",
      model: "Civic",
      transmission: "CVT",
      plate: "BA 4243 LL",
      year: 2015,
      driver_service: false,
      rent_per_day: 1000000,
      capacity: 4,
      type: "Sedan",
      category: "medium",
      options: JSON.stringify([
        "CD (Single Disc)",
        "Airbag: Passenger",
        "A/C: Front",
        "Power Locks",
        "Navigation",
        "Rear Window Defroster",
        "MP3 (Single Disc)",
        "Airbag: Side",
      ]),
      specs: JSON.stringify([
        "Electric speed-sensitive variable-assist pwr steering",
        "Steel side-door impact beams",
        "Dual bright exhaust tips",
        "Remote fuel lid release",
        "Traveler/mini trip computer",
      ]),
      description:
        "Electric speed-sensitive variable-assist pwr steering. Steel side-door impact beams. Dual bright exhaust tips.",
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);
}
